
function KeyValueMap(){var keysToIndex={__indexToValue:[],__indexToKeys:[]};var activeEnum=[];var tableLength=0;var self=this;this.get=function(key){if(typeof keysToIndex[key]=='number'){return keysToIndex.__indexToValue[keysToIndex[key]];}
else{return null;}};this.put=function(key,value){if(typeof keysToIndex[key]=='number'){keysToIndex.__indexToValue[keysToIndex[key]]=value;}
else{keysToIndex[key]=tableLength;keysToIndex.__indexToValue[tableLength]=value;keysToIndex.__indexToKeys[tableLength++]=key;}};KeyValueMap.prototype.containsKey=function(testKey){return(this.get(testKey)!=null);}}
PAYPAL.namespace("common");PAYPAL.namespace("bp");PAYPAL.namespace("ks");PAYPAL.common.appendField=function(formName,fieldName,fieldValue){var myForm=document.forms[formName];var field=document.createElement('input');field.setAttribute("type","hidden");field.setAttribute("id",fieldName);field.setAttribute("name",fieldName);if(fieldValue!==undefined){field.setAttribute("value",fieldValue);}
myForm.appendChild(field);};PAYPAL.bp={scriptVersion:1,attributeArray:[["a1","ScriptEngineMajorVersion()"],["a2","ScriptEngineMinorVersion()"],["a3","ScriptEngineBuildVersion()"],["a4","navigator.appCodeName"],["a5","navigator.appName"],["a6","navigator.appVersion"],["a7","helper.exec(['navigator.productSub','navigator.appMinorVersion'])"],["a8","navigator.browserLanguage"],["a9","navigator.cookieEnabled"],["a10","helper.exec(['navigator.oscpu','navigator.cpuClass'])"],["a11","navigator.onLine"],["a12","navigator.platform"],["a13","navigator.systemLanguage"],["a14","navigator.userAgent"],["a15","navigator.javaEnabled()"],["a16","helper.exec(['navigator.language', 'navigator.userLanguage'])"],["a17","document.defaultCharset"],["a18","document.domain"],["a19","screen.deviceXDPI"],["a20","screen.deviceYDPI"],["a21","screen.fontSmoothingEnabled"],["a22","screen.updateInterval"],["a23","screen.width"],["a24","screen.height"],["a25","screen.colorDepth"],["a26","screen.availHeight"],["a27","screen.availwidth"],["a28","kgObject.clientTime"],["a29","kgObject.clientTimeZone()"],["a30","kgObject.clientSoftware()"],["a31","kgHelper.isAJAXSupported()"],["a32","kgHelper.getCPU()"],["a33","kgHelper.isCssSupported()"],["a34","kgHelper.isDotNetSupported()"],["a35","kgHelper.isGearsInstalled()"],["a36","kgHelper.getGeoLocation()"],["a37","kgHelper.hasGoogleChrome()"],["a38","kgHelper.isOnline()"],["a39","kgHelper.hasOpenOffice()"],["a40","kgHelper.getOperatingSystem()"],["a41","kgHelper.isWebKitSupported()"],["a42","kgHelper.hasEvilPlugin()"]],EbayKgClientInfoHelper:function(){this.isAJAXSupported=function(){var r;try{r=new XMLHttpRequest();}catch(e){try{r=new ActiveXObject("Msxml2.XMLHTTP");}catch(e){try{r=new ActiveXObject("Microsoft.XMLHTTP");}catch(e){return"na";}}}
return(r)?"yes":"no";}
this.getCPU=function(){if(typeof(navigator.cpuClass)!="undefined"&&navigator.cpuClass!=""){var cpu=navigator.cpuClass;var ua=navigator.userAgent;if(ua.indexOf("WOW")>0){cpu="wow64";}
return cpu;}else
return"na";}
this.isCssSupported=function(){var _d=document.createElement("div");_d.id="css_test";_d.style.color="red";document.body.appendChild(_d);var xx=document.getElementById("css_test");if(xx.currentStyle){var res=xx.currentStyle["color"]!=_d.style.color?"no":"yes";document.body.removeChild(_d);return res;}
else
return("na");}
this.isDotNetSupported=function(){var idotnet=false
if(navigator.plugins["Windows Presentation Foundation"]){idotnet=true;}
return(idotnet)?"yes":"no";}
this.getGeoLocation=function(){return("geolocation"in navigator)?"yes":"no";}
this.isGearsInstalled=function(){return(window.google&&google.gears)?"yes":"no";}
this.hasGoogleChrome=function(){var i_chrome;i_chrome=navigator.userAgent.toLowerCase().indexOf("chrome")>-1;return(i_chrome)?"yes":"no";}
this.isOnline=function(){if(typeof(navigator.onLine)!="undefined"){return(navigator.onLine)?"online":"offline";}else
return"na";}
this.hasOpenOffice=function(){var i_ooo;if(navigator.plugins){if(navigator.plugins["OpenOffice.org Plug-in"]){i_ooo=true;}
return(i_ooo)?"yes":"no";}
else{return"na";}}
this.getOperatingSystem=function(){if(typeof(navigator.oscpu)=="string"){return(navigator.oscpu);}
else if(typeof(navigator.platform)!="undefined"){return(navigator.platform);}
else{return"na";}}
this.isWebKitSupported=function(){var ua=navigator.userAgent;webkit=RegExp("AppleWebKit/").test(ua);return webkit?"yes":"no";}
this.hasEvilPlugin=function(){return(navigator.plugins["Evil Plugin"])?"yes":"no";}},kgClientInfoHelper:function(){this.exec=function(possibles){for(var i=0;i<possibles.length;i++){try{var val=eval(possibles[i]);if(val){return val;}}
catch(e){}}
return"";};this.activeXDetect=function(componentClassID){var componentVersion=document.body.getComponentVersion('{'+componentClassID+'}','ComponentID');return(componentVersion!==null)?componentVersion:false;};this.stripIllegalChars=function(str){return str.toLowerCase().replace(/\n/g,"n").replace(/\x2F/g,"").replace(/\x5C{2}/g,"");};this.stripFullPath=function(tempFileName,lastDir){return tempFileName.replace(new RegExp(lastDir),"");};this.outputKeyValuePair=function(key,val){return key+"="+val;};},kgClientInfoObject:function(){this.clientTime=new Date();this.clientTimeZone=function(){var gmtHours=Math.round((new Date().getTimezoneOffset()/60)*(-1)*1000)/1000;return gmtHours;};this.clientSoftware=function(){var SEP='|';var PAIR='=';var ua=navigator.userAgent.toLowerCase();var opera=ua.indexOf("opera")>=0;var ie=ua.indexOf("msie")>=0&&!opera;var helper=new PAYPAL.bp.kgClientInfoHelper();var t="";var ht=new KeyValueMap();ht.put('npnul32.dll','def');ht.put('npqtplugin6.dll','qt6');ht.put('npqtplugin5.dll','qt5');ht.put('npqtplugin4.dll','qt4');ht.put('npqtplugin3.dll','qt3');ht.put('npqtplugin2.dll','qt2');ht.put('npqtplugin.dll','qt1');ht.put('nppdf32.dll','pdf');ht.put('NPSWF32.dll','swf');ht.put('NPJava11.dll','j11');ht.put('NPJava12.dll','j12');ht.put('NPJava13.dll','j13');ht.put('NPJava32.dll','j32');ht.put('NPJava14.dll','j14');ht.put('npoji600.dll','j61');ht.put('NPJava131_16.dll','j16');ht.put('NPOFFICE.DLL','mso');ht.put('npdsplay.dll','wpm');ht.put('npwmsdrm.dll','drm');ht.put('npdrmv2.dll','drn');ht.put('nprjplug.dll','rjl');ht.put('nppl3260.dll','rpl');ht.put('nprpjplug.dll','rpv');ht.put('npchime.dll','chm');ht.put('npCortona.dll','cor');ht.put('np32dsw.dll','dsw');ht.put('np32asw.dll','asw');if(navigator.plugins.length>0){temp="";moz="";key="";lastDir="Plugins";for(var g=0;g<navigator.plugins.length;g++){plugin=navigator.plugins[g];moz=helper.stripFullPath(plugin.filename,lastDir);key=ht.containsKey(moz);if(key){temp+=ht.get(moz)+SEP;}
else{temp+="";}}
t=helper.stripIllegalChars(temp);}
else if(navigator.mimeTypes.length>0){key="";for(var i=0;i<navigator.mimeTypes.length;i++){mimeType=navigator.mimeTypes[i];key=ht.containsKey(mimeType);if(key){t+=ht.get(mimeType)+PAIR+mimeType+SEP;}
else{t+="unknown"+PAIR+mimeType;}}}
else if(ie){names=["abk","wnt","aol","arb","chs","cht","dht","dhj","dan","dsh","heb","ie5","icw","ibe","iec","ieh","iee","jap","krn","lan","swf","shw","msn","wmp","obp","oex","net","pan","thi","tks","uni","vtc","vnm","mvm","vbs","wfd"];components=["7790769C-0471-11D2-AF11-00C04FA35D02","89820200-ECBD-11CF-8B85-00AA005B4340","47F67D00-9E55-11D1-BAEF-00C04FC2D130","76C19B38-F0C8-11CF-87CC-0020AFEECF20","76C19B34-F0C8-11CF-87CC-0020AFEECF20","76C19B33-F0C8-11CF-87CC-0020AFEECF20","9381D8F2-0288-11D0-9501-00AA00B911A5","4F216970-C90C-11D1-B5C7-0000F8051515","283807B5-2C60-11D0-A31D-00AA00B92C03","44BBA848-CC51-11CF-AAFA-00AA00B6015C","76C19B36-F0C8-11CF-87CC-0020AFEECF20","89820200-ECBD-11CF-8B85-00AA005B4383","5A8D6EE0-3E18-11D0-821E-444553540000","630B1DA0-B465-11D1-9948-00C04F98BBC9","08B0E5C0-4FCB-11CF-AAA5-00401C608555","45EA75A0-A269-11D1-B5BF-0000F8051515","DE5AED00-A4BF-11D1-9948-00C04F98BBC9","76C19B30-F0C8-11CF-87CC-0020AFEECF20","76C19B31-F0C8-11CF-87CC-0020AFEECF20","76C19B50-F0C8-11CF-87CC-0020AFEECF20","D27CDB6E-AE6D-11CF-96B8-444553540000","2A202491-F00D-11CF-87CC-0020AFEECF20","5945C046-LE7D-LLDL-BC44-00C04FD912BE","22D6F312-B0F6-11D0-94AB-0080C74C7E95","3AF36230-A269-11D1-B5BF-0000F8051515","44BBA840-CC51-11CF-AAFA-00AA00B6015C","44BBA842-CC51-11CF-AAFA-00AA00B6015B","76C19B32-F0C8-11CF-87CC-0020AFEECF20","76C19B35-F0C8-11CF-87CC-0020AFEECF20","CC2A9BA0-3BDD-11D0-821E-444553540000","3BF42070-B3B1-11D1-B5C5-0000F8051515","10072CEC-8CC1-11D1-986E-00A0C955B42F","76C19B37-F0C8-11CF-87CC-0020AFEECF20","08B0E5C0-4FCB-11CF-AAA5-00401C608500","4F645220-306D-11D2-995D-00C04F98BBC9","73FA19D0-2D75-11D2-995D-00C04F98BBC9"];document.body.addBehavior("#default#clientCaps");for(i=0;i<components.length;i++){ver=helper.activeXDetect(components[i]);var name=names[i];if(ver){t+=name+PAIR+ver+SEP;}
else{t+="";}}}
return t;};},init:function(formName,fieldName){var infoStr="";var kgHelper=new PAYPAL.bp.EbayKgClientInfoHelper();var helper=new PAYPAL.bp.kgClientInfoHelper();var kgObject=new PAYPAL.bp.kgClientInfoObject();for(var k=0;k<PAYPAL.bp.attributeArray.length;k++){var paramStr=PAYPAL.bp.attributeArray[k][0];var paramExp=PAYPAL.bp.attributeArray[k][1];var val="";try{val=eval(paramExp);if(typeof(val)=='undefined'){val="na";}}catch(e){val="na";}
infoStr+=helper.outputKeyValuePair(paramStr,val)+"~";}
PAYPAL.common.appendField(formName,fieldName);document.getElementById(fieldName).value="v="+PAYPAL.bp.scriptVersion+";"+infoStr;}};PAYPAL.ks={scriptVersion:1,init:function(formName,cFieldId,sFieldName){PAYPAL.common.appendField(formName,sFieldName);var ks=new this.handler(cFieldId,sFieldName);YAHOO.util.Event.addListener(cFieldId,"keydown",function(e){ks.capture(e);});YAHOO.util.Event.addListener(cFieldId,"keyup",function(e){ks.capture(e);});},handler:function(cFieldId,sFieldName){this.cFieldId=cFieldId;this.sFieldName=sFieldName;this.baseTime=new Date().getTime();this.keyIndex=0;this.keyIndexArray=[];this.storageArray=[];this.ignoreArray={"9":"tab","16":"shift","17":"ctrl","18":"alt"};this.keeperArray={"8":"bkspace","46":"delete"};this.capture=function(e){var keynum;var delta;if(window.event){keynum=e.keyCode;}
else if(e.which){keynum=e.which;}
if(!(keynum in this.ignoreArray)){var currTime=new Date().getTime();delta=currTime-this.baseTime;this.baseTime=currTime;if(keynum in this.keeperArray){if(e.type=="keydown"){this.storageArray.push("Dk"+keynum+":"+delta);}
else if(e.type=="keyup"){this.storageArray.push("Uk"+keynum+":"+delta);}}
else{if(e.type=="keydown"){this.storageArray.push("Di"+this.keyIndex+":"+delta);this.keyIndexArray[keynum]=this.keyIndex;this.keyIndex++;}
else if(e.type=="keyup"){this.storageArray.push("Ui"+this.keyIndexArray[keynum]+":"+delta);}}
var inputField=document.getElementById(this.cFieldId);document.getElementById(this.sFieldName).value="v="+PAYPAL.ks.scriptVersion+";"+"l="+inputField.value.length+";"+this.storageArray.join("");}};}};